application: kaigi-tao
version: 1
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /static/fonts
  static_dir: static/fonts
  mime_type: application/x-font-ttf

- url: /static
  static_dir: static

- url: /.*
  script: app.application

builtins:
- appstats: on

libraries:
- name: django
  version: latest
